### PR TITLE
feat: Visibility toggle for PasswordInput

### LINKED ISSUE #376: new/PasswordInputToggle
**Describe the behavior**
Currently, there is no option to include a toggle password input in fuselage.

**Additional Context**
Working on it!

### PR DESCRIPTION
**Pull request by im-adithya**
This PR closes #376 

https://user-images.githubusercontent.com/64399555/105881920-15c4a080-602b-11eb-9413-fd24c4bc49bf.mp4

### CODE REVIEW

**Comment by im-adithya** [comment]
@gabriellsh @MartinSchoeler @ggazzo Can you please check this and suggest changes if any?

**Review by gabriellsh — CHANGES_REQUESTED** [review]
Hey, nice job! Can you make this changes to the password input field itself? I don't think we should have 2 components for passwords.

Also, you got to create the stories for the storybook (`yarn storybook`), and update loki afterwards (`yarn update-storybook`). Thanks!

**Comment by im-adithya** [comment]
> Hey, nice job! Can you make this changes to the password input field itself? I don't think we should have 2 components for passwords.
> 
> Also, you got to create the stories for the storybook (`yarn storybook`), and update loki afterwards (`yarn update-storybook`). Thanks!

Sure @gabriellsh 😄

**Comment by im-adithya** [comment]
@gabriellsh I have made the changes. But what should I change in the stories? (Now that we made changes to PasswordInput itself... Should I add some info about the toggle property?)

**Comment by gabriellsh** [comment]
Would be nice to have one story for the hidden and one for the text showing (with some default text of course). This way loki can test for the visual behavior.

**Comment by im-adithya** [comment]
Done @gabriellsh! Please review it :)

**Comment by im-adithya** [comment]
@tassoevan can you please review this as well? :)

**Comment by tassoevan** [comment]
@im-adithya Is the toggle button accessible by tab navigation?

**Comment by im-adithya** [comment]
> @im-adithya Is the toggle button accessible by tab navigation?

No @tassoevan

**Review by gabriellsh — APPROVED** [review]

**Pull request merged**
